# App metadata and version
name: renalpal
description: "RenalPal – Your trusted kidney health companion app."
publish_to: 'none'
version: 1.1.0+2


# Dart SDK requirement
environment:
  sdk: ^3.8.1

# Core dependencies for the app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  firebase_core: ^3.12.0
  cloud_firestore: ^5.3.0
  package_info_plus: ^4.0.0

# Development tools and testing
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

# Launcher icon settings
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#35c8a4"
  adaptive_icon_foreground: "assets/icon/logo.png"

# Native splash screen configuration
flutter_native_splash:
  image: "assets/icon/splash_logo.png"
  color: "#ffffff"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit

  android_12:
    image: "assets/icon/splash_logo2.png"
    icon_background_color: "#ffffff"

# Flutter settings, assets, and fonts
flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png
    - assets/icon/splash_logo.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
