// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZQ-BPIn2jThL0-XCZVCohTVIwLgDW_w',
    appId: '1:28926085941:web:e65a0033557019507b1a7c',
    messagingSenderId: '28926085941',
    projectId: 'renalpal',
    authDomain: 'renalpal.firebaseapp.com',
    storageBucket: 'renalpal.firebasestorage.app',
    measurementId: 'G-719T1KXRE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACKTFxzU669mHNCM7_Ep4eo_3O5ue_u0g',
    appId: '1:28926085941:android:6fd79a261073ba0e7b1a7c',
    messagingSenderId: '28926085941',
    projectId: 'renalpal',
    storageBucket: 'renalpal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HLAvhCCsuLeQ-jvUwJlhtlJEHYwpcyE',
    appId: '1:28926085941:ios:ee7155cafc41385e7b1a7c',
    messagingSenderId: '28926085941',
    projectId: 'renalpal',
    storageBucket: 'renalpal.firebasestorage.app',
    iosBundleId: 'com.example.flutterApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2HLAvhCCsuLeQ-jvUwJlhtlJEHYwpcyE',
    appId: '1:28926085941:ios:ee7155cafc41385e7b1a7c',
    messagingSenderId: '28926085941',
    projectId: 'renalpal',
    storageBucket: 'renalpal.firebasestorage.app',
    iosBundleId: 'com.example.flutterApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChZQ-BPIn2jThL0-XCZVCohTVIwLgDW_w',
    appId: '1:28926085941:web:1d034e7951fbcd047b1a7c',
    messagingSenderId: '28926085941',
    projectId: 'renalpal',
    authDomain: 'renalpal.firebaseapp.com',
    storageBucket: 'renalpal.firebasestorage.app',
    measurementId: 'G-07CGVD5YTW',
  );
}
